// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PushMsgReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMsgReq) Reset()         { *m = PushMsgReq{} }
func (m *PushMsgReq) String() string { return proto.CompactTextString(m) }
func (*PushMsgReq) ProtoMessage()    {}
func (*PushMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *PushMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsgReq.Unmarshal(m, b)
}
func (m *PushMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsgReq.Marshal(b, m, deterministic)
}
func (m *PushMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsgReq.Merge(m, src)
}
func (m *PushMsgReq) XXX_Size() int {
	return xxx_messageInfo_PushMsgReq.Size(m)
}
func (m *PushMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsgReq proto.InternalMessageInfo

func (m *PushMsgReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *PushMsgReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PushMsgReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type PushMsgReply struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMsgReply) Reset()         { *m = PushMsgReply{} }
func (m *PushMsgReply) String() string { return proto.CompactTextString(m) }
func (*PushMsgReply) ProtoMessage()    {}
func (*PushMsgReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *PushMsgReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsgReply.Unmarshal(m, b)
}
func (m *PushMsgReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsgReply.Marshal(b, m, deterministic)
}
func (m *PushMsgReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsgReply.Merge(m, src)
}
func (m *PushMsgReply) XXX_Size() int {
	return xxx_messageInfo_PushMsgReply.Size(m)
}
func (m *PushMsgReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsgReply.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsgReply proto.InternalMessageInfo

func (m *PushMsgReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Request struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*PushMsgReq)(nil), "PushMsgReq")
	proto.RegisterType((*PushMsgReply)(nil), "PushMsgReply")
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x5f, 0x4b, 0xc3, 0x30,
	0x14, 0xc5, 0xd9, 0xdf, 0xb6, 0x77, 0x0a, 0x72, 0x9f, 0x4a, 0x99, 0x30, 0x02, 0x45, 0x9f, 0x02,
	0xce, 0x4f, 0x30, 0xdf, 0x07, 0x12, 0x44, 0xc1, 0xb7, 0xda, 0x5e, 0x6a, 0xd8, 0x9a, 0x9b, 0x35,
	0xa9, 0xe0, 0xb7, 0x17, 0x43, 0x5b, 0x11, 0x87, 0x6f, 0xbf, 0x93, 0x1c, 0xce, 0x39, 0x09, 0x24,
	0x85, 0xd5, 0xd2, 0xb6, 0xec, 0x59, 0x3c, 0x03, 0x3c, 0x76, 0xee, 0x7d, 0xef, 0x6a, 0x45, 0x27,
	0xcc, 0x20, 0xee, 0x1c, 0xb5, 0xa6, 0x68, 0x28, 0x9d, 0x6c, 0x26, 0xb7, 0x89, 0x1a, 0x35, 0xa6,
	0x10, 0x95, 0x6c, 0x3c, 0x19, 0x9f, 0x4e, 0xc3, 0xd5, 0x20, 0x11, 0x61, 0x5e, 0x72, 0x45, 0xe9,
	0x2c, 0x1c, 0x07, 0x16, 0x1b, 0xb8, 0x18, 0x73, 0xed, 0xf1, 0x13, 0xaf, 0x60, 0xd6, 0xb8, 0xba,
	0x0f, 0xfd, 0x46, 0x91, 0x43, 0xa4, 0xe8, 0xd4, 0x91, 0xf3, 0xff, 0xd5, 0x8a, 0x35, 0xc4, 0x8a,
	0x9c, 0x65, 0xe3, 0xe8, 0x6f, 0xc8, 0x56, 0xc1, 0x62, 0x57, 0x35, 0xda, 0x60, 0x0e, 0x51, 0xdf,
	0x87, 0x2b, 0xf9, 0xf3, 0xa2, 0xec, 0x52, 0xfe, 0x9a, 0x21, 0x60, 0xf5, 0x54, 0x1c, 0xe8, 0x85,
	0xdb, 0x83, 0x36, 0x35, 0xc6, 0xb2, 0x9f, 0x90, 0x25, 0x72, 0x68, 0xd9, 0xde, 0xc0, 0x72, 0x57,
	0x7a, 0xcd, 0x06, 0xaf, 0x47, 0x3a, 0x6b, 0xcc, 0x61, 0xb1, 0xe7, 0x8a, 0x8e, 0xb8, 0x1e, 0xe0,
	0x9c, 0xed, 0x61, 0xfe, 0x3a, 0xfd, 0xb8, 0x7b, 0x5b, 0x86, 0xff, 0xbe, 0xff, 0x0a, 0x00, 0x00,
	0xff, 0xff, 0x5a, 0xf1, 0xf2, 0x86, 0x7c, 0x01, 0x00, 0x00,
}
